[workspace]
members = [
    "attributes",
    "backtrace",
]

[workspace.metadata.release]
pre-release-commit-message = "chore: Release version {{version}}"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = true
allow-branch = ["main"]
